//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("transitoModel", "FK__accidente__idcon__09DE7BCC", "conductor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(negocio.conductor), "accidente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(negocio.accidente), true)]
[assembly: EdmRelationshipAttribute("transitoModel", "FK__accidente__idofo__08EA5793", "oficial", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(negocio.oficial), "accidente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(negocio.accidente), true)]

#endregion

namespace negocio
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class transitoEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto transitoEntities usando la cadena de conexión encontrada en la sección 'transitoEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public transitoEntities() : base("name=transitoEntities", "transitoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto transitoEntities.
        /// </summary>
        public transitoEntities(string connectionString) : base(connectionString, "transitoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto transitoEntities.
        /// </summary>
        public transitoEntities(EntityConnection connection) : base(connection, "transitoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<accidente> accidente
        {
            get
            {
                if ((_accidente == null))
                {
                    _accidente = base.CreateObjectSet<accidente>("accidente");
                }
                return _accidente;
            }
        }
        private ObjectSet<accidente> _accidente;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<conductor> conductor
        {
            get
            {
                if ((_conductor == null))
                {
                    _conductor = base.CreateObjectSet<conductor>("conductor");
                }
                return _conductor;
            }
        }
        private ObjectSet<conductor> _conductor;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<oficial> oficial
        {
            get
            {
                if ((_oficial == null))
                {
                    _oficial = base.CreateObjectSet<oficial>("oficial");
                }
                return _oficial;
            }
        }
        private ObjectSet<oficial> _oficial;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<VistaConductor> VistaConductor
        {
            get
            {
                if ((_VistaConductor == null))
                {
                    _VistaConductor = base.CreateObjectSet<VistaConductor>("VistaConductor");
                }
                return _VistaConductor;
            }
        }
        private ObjectSet<VistaConductor> _VistaConductor;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<VistaOficial> VistaOficial
        {
            get
            {
                if ((_VistaOficial == null))
                {
                    _VistaOficial = base.CreateObjectSet<VistaOficial>("VistaOficial");
                }
                return _VistaOficial;
            }
        }
        private ObjectSet<VistaOficial> _VistaOficial;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet accidente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToaccidente(accidente accidente)
        {
            base.AddObject("accidente", accidente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet conductor. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToconductor(conductor conductor)
        {
            base.AddObject("conductor", conductor);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet oficial. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTooficial(oficial oficial)
        {
            base.AddObject("oficial", oficial);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet VistaConductor. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVistaConductor(VistaConductor vistaConductor)
        {
            base.AddObject("VistaConductor", vistaConductor);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet VistaOficial. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVistaOficial(VistaOficial vistaOficial)
        {
            base.AddObject("VistaOficial", vistaOficial);
        }

        #endregion

        #region Importaciones de funciones
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="fecha1">No hay documentación de metadatos disponible.</param>
        public int pfecha(Nullable<global::System.DateTime> fecha1)
        {
            ObjectParameter fecha1Parameter;
            if (fecha1.HasValue)
            {
                fecha1Parameter = new ObjectParameter("fecha1", fecha1);
            }
            else
            {
                fecha1Parameter = new ObjectParameter("fecha1", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction("pfecha", fecha1Parameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public int pOficial()
        {
            return base.ExecuteFunction("pOficial");
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public int pConductor()
        {
            return base.ExecuteFunction("pConductor");
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="transitoModel", Name="accidente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accidente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto accidente.
        /// </summary>
        /// <param name="idaccidente">Valor inicial de la propiedad idaccidente.</param>
        /// <param name="zona">Valor inicial de la propiedad zona.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        public static accidente Createaccidente(global::System.Int32 idaccidente, global::System.String zona, global::System.DateTime fecha)
        {
            accidente accidente = new accidente();
            accidente.idaccidente = idaccidente;
            accidente.zona = zona;
            accidente.fecha = fecha;
            return accidente;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idaccidente
        {
            get
            {
                return _idaccidente;
            }
            set
            {
                if (_idaccidente != value)
                {
                    OnidaccidenteChanging(value);
                    ReportPropertyChanging("idaccidente");
                    _idaccidente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idaccidente");
                    OnidaccidenteChanged();
                }
            }
        }
        private global::System.Int32 _idaccidente;
        partial void OnidaccidenteChanging(global::System.Int32 value);
        partial void OnidaccidenteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zona
        {
            get
            {
                return _zona;
            }
            set
            {
                OnzonaChanging(value);
                ReportPropertyChanging("zona");
                _zona = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("zona");
                OnzonaChanged();
            }
        }
        private global::System.String _zona;
        partial void OnzonaChanging(global::System.String value);
        partial void OnzonaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idofocial
        {
            get
            {
                return _idofocial;
            }
            set
            {
                OnidofocialChanging(value);
                ReportPropertyChanging("idofocial");
                _idofocial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idofocial");
                OnidofocialChanged();
            }
        }
        private Nullable<global::System.Int32> _idofocial;
        partial void OnidofocialChanging(Nullable<global::System.Int32> value);
        partial void OnidofocialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idconductor
        {
            get
            {
                return _idconductor;
            }
            set
            {
                OnidconductorChanging(value);
                ReportPropertyChanging("idconductor");
                _idconductor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idconductor");
                OnidconductorChanged();
            }
        }
        private Nullable<global::System.Int32> _idconductor;
        partial void OnidconductorChanging(Nullable<global::System.Int32> value);
        partial void OnidconductorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("transitoModel", "FK__accidente__idcon__09DE7BCC", "conductor")]
        public conductor conductor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<conductor>("transitoModel.FK__accidente__idcon__09DE7BCC", "conductor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<conductor>("transitoModel.FK__accidente__idcon__09DE7BCC", "conductor").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<conductor> conductorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<conductor>("transitoModel.FK__accidente__idcon__09DE7BCC", "conductor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<conductor>("transitoModel.FK__accidente__idcon__09DE7BCC", "conductor", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("transitoModel", "FK__accidente__idofo__08EA5793", "oficial")]
        public oficial oficial
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<oficial>("transitoModel.FK__accidente__idofo__08EA5793", "oficial").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<oficial>("transitoModel.FK__accidente__idofo__08EA5793", "oficial").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<oficial> oficialReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<oficial>("transitoModel.FK__accidente__idofo__08EA5793", "oficial");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<oficial>("transitoModel.FK__accidente__idofo__08EA5793", "oficial", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="transitoModel", Name="conductor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class conductor : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto conductor.
        /// </summary>
        /// <param name="idconductor">Valor inicial de la propiedad idconductor.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="apellido">Valor inicial de la propiedad apellido.</param>
        /// <param name="direccion">Valor inicial de la propiedad direccion.</param>
        public static conductor Createconductor(global::System.Int32 idconductor, global::System.String nombre, global::System.String apellido, global::System.String direccion)
        {
            conductor conductor = new conductor();
            conductor.idconductor = idconductor;
            conductor.nombre = nombre;
            conductor.apellido = apellido;
            conductor.direccion = direccion;
            return conductor;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idconductor
        {
            get
            {
                return _idconductor;
            }
            set
            {
                if (_idconductor != value)
                {
                    OnidconductorChanging(value);
                    ReportPropertyChanging("idconductor");
                    _idconductor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idconductor");
                    OnidconductorChanged();
                }
            }
        }
        private global::System.Int32 _idconductor;
        partial void OnidconductorChanging(global::System.Int32 value);
        partial void OnidconductorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ci
        {
            get
            {
                return _ci;
            }
            set
            {
                OnciChanging(value);
                ReportPropertyChanging("ci");
                _ci = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ci");
                OnciChanged();
            }
        }
        private Nullable<global::System.Int32> _ci;
        partial void OnciChanging(Nullable<global::System.Int32> value);
        partial void OnciChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private Nullable<global::System.Int32> _telefono;
        partial void OntelefonoChanging(Nullable<global::System.Int32> value);
        partial void OntelefonoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("transitoModel", "FK__accidente__idcon__09DE7BCC", "accidente")]
        public EntityCollection<accidente> accidente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<accidente>("transitoModel.FK__accidente__idcon__09DE7BCC", "accidente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<accidente>("transitoModel.FK__accidente__idcon__09DE7BCC", "accidente", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="transitoModel", Name="oficial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class oficial : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto oficial.
        /// </summary>
        /// <param name="idoficial">Valor inicial de la propiedad idoficial.</param>
        /// <param name="nombreO">Valor inicial de la propiedad nombreO.</param>
        /// <param name="direccionO">Valor inicial de la propiedad direccionO.</param>
        /// <param name="rango">Valor inicial de la propiedad rango.</param>
        public static oficial Createoficial(global::System.Int32 idoficial, global::System.String nombreO, global::System.String direccionO, global::System.String rango)
        {
            oficial oficial = new oficial();
            oficial.idoficial = idoficial;
            oficial.nombreO = nombreO;
            oficial.direccionO = direccionO;
            oficial.rango = rango;
            return oficial;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idoficial
        {
            get
            {
                return _idoficial;
            }
            set
            {
                if (_idoficial != value)
                {
                    OnidoficialChanging(value);
                    ReportPropertyChanging("idoficial");
                    _idoficial = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idoficial");
                    OnidoficialChanged();
                }
            }
        }
        private global::System.Int32 _idoficial;
        partial void OnidoficialChanging(global::System.Int32 value);
        partial void OnidoficialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreO
        {
            get
            {
                return _nombreO;
            }
            set
            {
                OnnombreOChanging(value);
                ReportPropertyChanging("nombreO");
                _nombreO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombreO");
                OnnombreOChanged();
            }
        }
        private global::System.String _nombreO;
        partial void OnnombreOChanging(global::System.String value);
        partial void OnnombreOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccionO
        {
            get
            {
                return _direccionO;
            }
            set
            {
                OndireccionOChanging(value);
                ReportPropertyChanging("direccionO");
                _direccionO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccionO");
                OndireccionOChanged();
            }
        }
        private global::System.String _direccionO;
        partial void OndireccionOChanging(global::System.String value);
        partial void OndireccionOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rango
        {
            get
            {
                return _rango;
            }
            set
            {
                OnrangoChanging(value);
                ReportPropertyChanging("rango");
                _rango = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rango");
                OnrangoChanged();
            }
        }
        private global::System.String _rango;
        partial void OnrangoChanging(global::System.String value);
        partial void OnrangoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellidoO
        {
            get
            {
                return _apellidoO;
            }
            set
            {
                OnapellidoOChanging(value);
                ReportPropertyChanging("apellidoO");
                _apellidoO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellidoO");
                OnapellidoOChanged();
            }
        }
        private global::System.String _apellidoO;
        partial void OnapellidoOChanging(global::System.String value);
        partial void OnapellidoOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private Nullable<global::System.Int32> _telefono;
        partial void OntelefonoChanging(Nullable<global::System.Int32> value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ci
        {
            get
            {
                return _ci;
            }
            set
            {
                OnciChanging(value);
                ReportPropertyChanging("ci");
                _ci = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ci");
                OnciChanged();
            }
        }
        private Nullable<global::System.Int32> _ci;
        partial void OnciChanging(Nullable<global::System.Int32> value);
        partial void OnciChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("transitoModel", "FK__accidente__idofo__08EA5793", "accidente")]
        public EntityCollection<accidente> accidente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<accidente>("transitoModel.FK__accidente__idofo__08EA5793", "accidente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<accidente>("transitoModel.FK__accidente__idofo__08EA5793", "accidente", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="transitoModel", Name="VistaConductor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VistaConductor : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto VistaConductor.
        /// </summary>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="apellido">Valor inicial de la propiedad apellido.</param>
        /// <param name="direccion">Valor inicial de la propiedad direccion.</param>
        public static VistaConductor CreateVistaConductor(global::System.String nombre, global::System.String apellido, global::System.String direccion)
        {
            VistaConductor vistaConductor = new VistaConductor();
            vistaConductor.nombre = nombre;
            vistaConductor.apellido = apellido;
            vistaConductor.direccion = direccion;
            return vistaConductor;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                if (_nombre != value)
                {
                    OnnombreChanging(value);
                    ReportPropertyChanging("nombre");
                    _nombre = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nombre");
                    OnnombreChanged();
                }
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                if (_apellido != value)
                {
                    OnapellidoChanging(value);
                    ReportPropertyChanging("apellido");
                    _apellido = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("apellido");
                    OnapellidoChanged();
                }
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                if (_direccion != value)
                {
                    OndireccionChanging(value);
                    ReportPropertyChanging("direccion");
                    _direccion = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("direccion");
                    OndireccionChanged();
                }
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ci
        {
            get
            {
                return _ci;
            }
            set
            {
                OnciChanging(value);
                ReportPropertyChanging("ci");
                _ci = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ci");
                OnciChanged();
            }
        }
        private Nullable<global::System.Int32> _ci;
        partial void OnciChanging(Nullable<global::System.Int32> value);
        partial void OnciChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private Nullable<global::System.Int32> _telefono;
        partial void OntelefonoChanging(Nullable<global::System.Int32> value);
        partial void OntelefonoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="transitoModel", Name="VistaOficial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VistaOficial : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto VistaOficial.
        /// </summary>
        /// <param name="nombreO">Valor inicial de la propiedad nombreO.</param>
        /// <param name="direccionO">Valor inicial de la propiedad direccionO.</param>
        /// <param name="rango">Valor inicial de la propiedad rango.</param>
        public static VistaOficial CreateVistaOficial(global::System.String nombreO, global::System.String direccionO, global::System.String rango)
        {
            VistaOficial vistaOficial = new VistaOficial();
            vistaOficial.nombreO = nombreO;
            vistaOficial.direccionO = direccionO;
            vistaOficial.rango = rango;
            return vistaOficial;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreO
        {
            get
            {
                return _nombreO;
            }
            set
            {
                if (_nombreO != value)
                {
                    OnnombreOChanging(value);
                    ReportPropertyChanging("nombreO");
                    _nombreO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nombreO");
                    OnnombreOChanged();
                }
            }
        }
        private global::System.String _nombreO;
        partial void OnnombreOChanging(global::System.String value);
        partial void OnnombreOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccionO
        {
            get
            {
                return _direccionO;
            }
            set
            {
                if (_direccionO != value)
                {
                    OndireccionOChanging(value);
                    ReportPropertyChanging("direccionO");
                    _direccionO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("direccionO");
                    OndireccionOChanged();
                }
            }
        }
        private global::System.String _direccionO;
        partial void OndireccionOChanging(global::System.String value);
        partial void OndireccionOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rango
        {
            get
            {
                return _rango;
            }
            set
            {
                if (_rango != value)
                {
                    OnrangoChanging(value);
                    ReportPropertyChanging("rango");
                    _rango = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("rango");
                    OnrangoChanged();
                }
            }
        }
        private global::System.String _rango;
        partial void OnrangoChanging(global::System.String value);
        partial void OnrangoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellidoO
        {
            get
            {
                return _apellidoO;
            }
            set
            {
                OnapellidoOChanging(value);
                ReportPropertyChanging("apellidoO");
                _apellidoO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellidoO");
                OnapellidoOChanged();
            }
        }
        private global::System.String _apellidoO;
        partial void OnapellidoOChanging(global::System.String value);
        partial void OnapellidoOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private Nullable<global::System.Int32> _telefono;
        partial void OntelefonoChanging(Nullable<global::System.Int32> value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ci
        {
            get
            {
                return _ci;
            }
            set
            {
                OnciChanging(value);
                ReportPropertyChanging("ci");
                _ci = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ci");
                OnciChanged();
            }
        }
        private Nullable<global::System.Int32> _ci;
        partial void OnciChanging(Nullable<global::System.Int32> value);
        partial void OnciChanged();

        #endregion

    
    }

    #endregion

    
}
